spring:
  application:
    name: zuul-gateway-server

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org.hibernate.envers.audit_table_suffix: _log

server:
  servlet:
    context-path: /api/v1
  port: 8001

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ignoredServices: "*"
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
      sensitive-headers: Cookie,Set-Cookie
#     order-service:
#       path: /orders/**
#       service-id: order-service
#       sensitive-headers: Cookie,Set-Cookie
#    report-service:
#      path: /reports/**
#      service-id: report-service
#    admin-service:
#      path: /admin/**
#      service-id: admin-service

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


jwt:
  token:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYBaGO4rsvb6GK8HwqlS3dlgcPQLrNPbvjlG4mo5fPAgciAWi8YhJP22Cmd4Ec2u+yCeALgqUAvMvajnLjLtaD3cySWpb+PdNH7NoZYpJTXmsShpY4BlWpYm2Tn1c2Xd+RTojIZSYvfBAzcp6KGMDMm6FEao5bitIAmmzkY1WnzwIDAQAB
